import React from 'react';
import { Laptop, Briefcase, Layout as LayoutIcon, Code, Target, MonitorPlay, Box, Sun, Star } from 'lucide-react';
import { Course } from '../types';

export const ALL_COURSES: Course[] = [
  { 
    id: 1, 
    title: "Flutter Masterclass", 
    topic: "Development", 
    category: "IT & Software",
    tags: ["Development", "Mobile", "IT & Software"],
    progress: 75, 
    bgColor: "bg-card-pink", 
    icon: <Laptop size={16} strokeWidth={2.5} />, 
    categoryIcon: <Laptop size={14} strokeWidth={2} />,
    rating: 4.8,
    instructor: "Sarah Jenkins",
    description: "Learn to build cross-platform apps with Flutter and Dart.",
    students: "9,530",
    avatars: [ "https://randomuser.me/api/portraits/women/11.jpg", "https://randomuser.me/api/portraits/men/12.jpg" ]
  },
  { 
    id: 2, 
    title: "Powerful Business Writing", 
    topic: "Business", 
    category: "Business",
    tags: ["Business", "Writing", "Communication"],
    progress: 100, 
    bgColor: "bg-card-yellow", 
    icon: <Briefcase size={16} strokeWidth={2.5} />, 
    categoryIcon: <Briefcase size={14} strokeWidth={2} />,
    rating: 4.9,
    instructor: "Robert Brown",
    description: "Write concisely and effectively in a business environment.",
    students: "1,463",
    avatars: [ "https://randomuser.me/api/portraits/women/13.jpg", "https://randomuser.me/api/portraits/men/14.jpg" ]
  },
  { 
    id: 3, 
    title: "UI/UX Masterclass", 
    topic: "Design", 
    category: "Media Training",
    tags: ["Design", "UI/UX", "Product"],
    progress: 30, 
    bgColor: "bg-[#DCDDFF]", 
    icon: <LayoutIcon size={16} strokeWidth={2.5} />, 
    categoryIcon: <MonitorPlay size={14} strokeWidth={2} />,
    rating: 4.7,
    instructor: "Elena Gilbert",
    description: "Master the art of user interface and user experience design.",
    students: "6,726",
    avatars: [ "https://randomuser.me/api/portraits/women/15.jpg", "https://randomuser.me/api/portraits/men/16.jpg" ]
  },
  { 
    id: 4, 
    title: "Advanced Data Structures", 
    topic: "Development", 
    category: "IT & Software",
    tags: ["Development", "Algorithms", "Computer Science"],
    progress: 0, 
    bgColor: "bg-[#B2F0D1]", 
    icon: <Code size={16} strokeWidth={2.5} />, 
    categoryIcon: <Laptop size={14} strokeWidth={2} />,
    rating: 4.6,
    instructor: "David Miller",
    description: "Deep dive into complex data structures and algorithms.",
    students: "3,210",
    avatars: [ "https://randomuser.me/api/portraits/men/22.jpg" ]
  },
  { 
    id: 5, 
    title: "Agile Project Management", 
    topic: "Business", 
    category: "Business",
    tags: ["Business", "Management", "Agile"],
    progress: 100, 
    bgColor: "bg-[#E8E1F5]", 
    icon: <Target size={16} strokeWidth={2.5} />, 
    categoryIcon: <Briefcase size={14} strokeWidth={2} />,
    rating: 4.9,
    instructor: "Michael Scott",
    description: "Learn Agile methodologies to manage projects efficiently.",
    students: "5,400",
    avatars: [ "https://randomuser.me/api/portraits/men/33.jpg" ]
  },
  { 
    id: 6, 
    title: "React Performance Tuning", 
    topic: "Development", 
    category: "IT & Software",
    tags: ["Development", "Frontend", "React"],
    progress: 50, 
    bgColor: "bg-[#FBE6C2]", 
    icon: <Laptop size={16} strokeWidth={2.5} />, 
    categoryIcon: <Laptop size={14} strokeWidth={2} />,
    rating: 4.8,
    instructor: "Jessica Cheng",
    description: "Optimize your React applications for maximum speed.",
    students: "2,150",
    avatars: [ "https://randomuser.me/api/portraits/women/44.jpg" ]
  },
  {
    id: 7,
    bgColor: "bg-card-green",
    topic: "Design",
    category: "Interior",
    tags: ["Design", "Architecture", "Interior"],
    progress: 20,
    categoryIcon: <Box size={14} strokeWidth={2} />,
    rating: 5.0,
    title: "How to Design a Room in 10 Easy Steps",
    students: "8,735",
    avatars: [ "https://randomuser.me/api/portraits/women/33.jpg" ],
    instructor: "Kelly Wearstler",
    description: "Interior design fundamentals for everyone.",
    badge: <span className="bg-white text-[#1B1B1B] font-bold px-3 py-1.5 flex items-center gap-1.5 rounded-[12px] text-xs shadow-sm"><span className="text-[14px]">🔥</span> Top 10</span>
  },
  { 
    id: 8, 
    title: "Python for Data Science", 
    topic: "Development", 
    category: "Programming", 
    tags: ["Development", "Python", "Data Science"],
    progress: 65,
    rating: "4.8", 
    bgColor: "bg-card-purple", 
    avatars: ['https://randomuser.me/api/portraits/women/4.jpg', 'https://randomuser.me/api/portraits/men/5.jpg'], 
    students: "18.2k", 
    instructor: "Dr. Angela Yu"
  },
  { 
    id: 9, 
    title: "Digital Marketing 101", 
    topic: "Business", 
    category: "Marketing", 
    tags: ["Business", "Marketing", "Growth"],
    progress: 40,
    rating: "4.6", 
    bgColor: "bg-card-pink", 
    avatars: ['https://randomuser.me/api/portraits/women/7.jpg', 'https://randomuser.me/api/portraits/men/8.jpg'], 
    students: "8.4k", 
    instructor: "Seth Godin"
  }
];
